repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
    -   id: clang-format
        exclude: ^external/
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: check-merge-conflict
    -   id: trailing-whitespace
